src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 * @Vich\Uploadable
 */
class Annonces
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_on;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     */
    private $author;


    /**
     * @Vich\UploadableField(mapping="annonces_photos", fileNameProperty="photos")
     * @assert\File(
     * maxSize="10M", 
     * mimeTypes = {"image/png" , "image/jpg" , "image/JPG", "image/PNG"},
     * mimeTypesMessage = "Seules les images jpg et png sont acceptées"
     * )
     */
    private $photosFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photos;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
    public function getPhotosFile(): ?File
    {
        return $this->photosFile;
    }
    public function setPhotosFile(?File $photosFile = null): void
    {
        $this->photosFile = $photosFile;
    }

    public function getPhotos(): ?string
    {
        return $this->photos;
    }

    public function setPhotos(?string $photos): self
    {
        $this->photos = $photos;

        return $this;
    } 
}

src/Controller/LeboncoinController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;

class LeboncoinController extends AbstractController
{
    /**
     * @Route("/", name="leboncoin_index")
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->findBy([], ['created_on' => 'DESC']);
        $annonces = $paginator->paginate($annonces, $request->query->getInt('page', 1), 3);

        return $this->render('leboncoin/index.html.twig', ['annonces' => $annonces]);
    }

    /**
     * @Route("/add", name="leboncoin_add")
     */
    public function add(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        $annonces = new Annonces();
        $annonces->setCreatedOn(new \DateTime);
        $user = $this->getUser();
        $annonces->setAuthor($user);

        $form = $this->createFormBuilder($annonces)
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('price', MoneyType::class)
            ->add('photosFile', VichImageType::class, ['required' => false])
            ->add('submit', SubmitType::class, ['label' => 'Valider l\'annonce'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonces);
            $entityManager->flush();

            $this->addFlash('success', 'Your ad has been created !');

            return $this->redirectToRoute('leboncoin_index');
        }
        return $this->render('leboncoin/add.html.twig', ['addForm' => $form->createView()]);
    }
    /**
     * @Route("/annonce/{id}", name="leboncoin_annonce")
     */
    public function annonce($id)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->find($id);

        return $this->render('leboncoin/annonce.html.twig', ['annonce' => $annonces]);
    }
    /**
     * @Route("/delete/{id}", name="leboncoin_delete")
     */
    public function delete($id)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonce = $annonceRepository->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($annonce);
        $entityManager->flush();

        $this->addFlash('success', 'Your ad has been deleted !');

        return $this->redirectToRoute('leboncoin_index');
    }
    /**
     * @Route("/edit/{id}", name="leboncoin_edit")
     */
    public function edit($id, Request $request)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonce = $annonceRepository->find($id);

        $form = $this->createFormBuilder($annonce)
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('price', MoneyType::class)
            ->add('submit', SubmitType::class, ['label' => 'Editer l\'annonce'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            $this->addFlash('success', 'Your ad has been successfully modified !');

            return $this->redirectToRoute('leboncoin_annonce', ['id' => $annonce->getId()]);
        }

        return $this->render('leboncoin/edit.html.twig', ['editForm' => $form->createView()]);
    }
    /**
     * @Route("/compte/{id}", name="leboncoin_compte")
     */
    public function editCompte($id, Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        $user = $this->getUser();

        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->findBy(['author' => $user], ['created_on' => 'DESC']);

        $form = $this->createFormBuilder($user)
            ->add('password', PasswordType::class, ['mapped' => false])
            ->add('submit', SubmitType::class, ['label' => 'Editer votre mot de passe'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword($passwordEncoder->encodePassword($user, $form->get('password')->getData()));

            $entityManager = $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Your password has been changed !');

            return $this->redirectToRoute('leboncoin_compte', ['id' => $user->getId()]);
        }

        return $this->render('leboncoin/compte.html.twig', ['compteForm' => $form->createView(), 'annonces' => $annonces]);
    }
}

templates/leboncoin/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Write an ad
{% endblock %}

{% block body %}
	<header>
		<h1>
			Write your ad
		</h1>
	</header>
	{{ form(addForm) }}{% endblock %}

templates/leboncoin/annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Announcement page
{% endblock %}

{% block body %}
	<header>
		<h1 class="animate__animated animate__backInLeft">Your Ads
		</h1>
	</header>
	<div class="annonce">
		<h2>
			{{annonce.title}}
		</h2>
	</a>
	<p>
		{{annonce.content}}
	</p>
	<h3>
		Posted the :
		{{annonce.createdOn | date('d/m/Y h:i:s')}}
	</h3>
	Price :
	{{annonce.price}}€
	<p>
		seller :
		{% if annonce.author %}
			{{annonce.author.username}}
		{% endif %}
		{% if app.user and app.user == annonce.author %}
			<p>
				<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
					<button class="red">Delete</button>
				</a>
			</p>
			<p>
				<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
					<button class="green">Edit</button>
				</a>
			</p>
			<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
		{% endif %}
	</p>
</div>{% endblock %}

templates/leboncoin/compte.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modifiez votre compte
{% endblock %}

{% block body %}
	<header>
		<h1>
			Modifiez votre compte
		</h1>
	</header>
	<header>
		<h1 class="animate__animated animate__backInLeft">Your Ads
		</h1>
	</header>
	{{ form(compteForm) }}
	{% for annonce in annonces %}
		<div class="annonce">
			<h2>
				{{annonce.title}}
			</h2>
		</a>
		<p>
			{{annonce.content}}
		</p>
		<h3>
			Posted the :
			{{annonce.createdOn | date('d/m/Y h:i:s')}}
		</h3>
		Price :
		{{annonce.price}}€
		<p>
			seller :
			{% if annonce.author %}
				{{annonce.author.username}}
			{% endif %}
			{% if app.user and app.user == annonce.author %}
				<p>
					<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
						<button class="red">Delete</button>
					</a>
				</p>
				<p>
					<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
						<button class="green">Edit</button>
					</a>
				</p>
				<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
				</div>
			{% endif %}
		{% endfor %}
	</p>{% endblock %}

templates/leboncoin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modifiez votre annonce
{% endblock %}

{% block body %}
	<header>
		<h1>
			Modifiez votre annonce
		</h1>
	</header>
	{{ form(editForm) }}{% endblock %}

templates/leboncoin/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Home page
{% endblock %}

{% block body %}
	<header>
		<h1 class="animate__animated animate__backInLeft">Welcome to our online announcement site !
		</h1>
	</header>
	{% for annonce in annonces %}
		<div class="annonce">
			<a href="{{ path('leboncoin_annonce', {'id' : annonce.id }) }}">
				<h2>
					{{annonce.title}}
				</h2>
			</a>
			<p>
				{{annonce.content}}
			</p>
			<h3>
				Posted the :
				{{annonce.createdOn | date('d/m/Y h:i:s')}}
			</h3>
			Price :
			{{annonce.price}}€
			<p>
				seller :
				{% if annonce.author %}
					{{annonce.author.username}}
				</p>
			{% endif %}
			{% if app.user and app.user == annonce.author %}
				<p>
					<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
						<button class="red">Delete</button>
					</a>
				</p>
				<p>
					<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
						<button class="green">Edit</button>
					</a>
				</p>
				<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
			{% endif %}
		</div>
	{% endfor %}
	<div class="pagination">
		{{ knp_pagination_render(annonces) }}
	</div>
{% endblock %}